---
title: "Data Cleaning"
author: "Evian Lin"
date: "2020/12/29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```


```{r}
library(tidyverse)
```

The purpose of following codes is to clean the data we get in the previous file.

#Endorsing
```{r}
endorsing_positive_comments <- readRDS("data/positive_comments/endorsing_positive_comments")
endorsing_negative_comments <- readRDS("data/negative_comments/endorsing_negative_comments")
title <- readRDS("data/title_df/endorsing/title_df_endorsing_1221")

#endorsing.board <- endorsing_positive_comments %>% select(board)
#endorsing.board$board[,c("title")]
#names(endorsing_positive_comments)
#endorsing_pos <- tibble(endorsing_positive_comments %>% select(oriContent,cdate,sideType,agreeCount,disagreeCount),endorsing_positive_comments$board$title)
endorsing_pos <- endorsing_positive_comments %>%
    select(oriContent,cdate,sideType,agreeCount,disagreeCount) %>%
    mutate(title = endorsing_positive_comments$board$title)

endorsing_neg <- endorsing_negative_comments %>%
    select(oriContent,cdate,sideType,agreeCount,disagreeCount) %>%
    mutate(title = endorsing_negative_comments$board$title)


endorsing.df <- title %>%
    left_join(endorsing_pos, by =  c("titles" = "title")) %>%
    rbind(title %>% left_join(endorsing_neg, by = c("titles" = "title")))

saveRDS(endorsing.df, file = "data/clean/endorsing_df")
```


#Completed
```{r}
rm(list = ls())
completed_positive_comments <- readRDS("data/positive_comments/completed_positive_comments")
completed_negative_comments <- readRDS("data/negative_comments/completed_negative_comments")
title <- readRDS("data/title_df/title_df_completed")

completed_pos <- completed_positive_comments %>%
    select(oriContent,cdate,sideType,agreeCount,disagreeCount) %>%
    mutate(title = completed_positive_comments$board$title)

completed_neg <- completed_negative_comments %>%
    select(oriContent,cdate,sideType,agreeCount,disagreeCount) %>%
    mutate(title = completed_negative_comments$board$title)

completed.df <- title %>%
    left_join(completed_pos, by =  c("titles" = "title")) %>%
    rbind(title %>% left_join(completed_neg, by = c("titles" = "title")))

saveRDS(completed.df, file = "data/clean/completed_df")

```

#Unsuccessed
```{r}
rm(list = ls())
unsuccessed_positive_comments1 <- readRDS("data/positive_comments/unsuccessed_positive_comments_to_4086")

unsuccessed_positive_comments2 <- readRDS("data/positive_comments/unsuccessed_positive_comments_from_4087")

unsuccessed_positive_comments <- rbind(unsuccessed_positive_comments1,unsuccessed_positive_comments2)
    
unsuccessed_negative_comments <- readRDS("data/negative_comments/unsuccessed_negative_comments")
title <- readRDS("data/title_df/title_df_unsuccessed")

unsuccessed_pos <- unsuccessed_positive_comments %>%
    select(oriContent,cdate,sideType,agreeCount,disagreeCount) %>%
    mutate(title = unsuccessed_positive_comments$board$title)

unsuccessed_neg <- unsuccessed_negative_comments %>%
    select(oriContent,cdate,sideType,agreeCount,disagreeCount) %>%
    mutate(title = unsuccessed_negative_comments$board$title)

unsuccessed.df <- title %>%
    left_join(unsuccessed_pos, by =  c("titles" = "title")) %>%
    rbind(title %>% left_join(unsuccessed_neg, by = c("titles" = "title")))

saveRDS(unsuccessed.df, file = "data/clean/unsuccessed_df")
```
#patch0113
```{r}
com.content <- readRDS("data/content/completed_content")
uns.content <- readRDS("data/content/unsuccessed_content")

com.content <- com.content %>%
    mutate(content = str_replace(content, "提議內容或建議事項", "")) %>%
    separate("content", c("content","impact"), sep = "利益與影響")


uns.content <- uns.content %>%
    mutate(content = str_replace(content, "提議內容或建議事項", "")) %>%
    select(-test)

saveRDS(com.content, file = "data/content/completed_content")
saveRDS(uns.content, file = "data/content/unsuccessed_content")
```

